steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/data8x-scratch/otter-srv:$_TAG_NAME', '-t', 'gcr.io/data8x-scratch/otter-srv', '.' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/data8x-scratch/otter-srv']
images:
  - 'gcr.io/data8x-scratch/otter-srv:$_TAG_NAME'
  - 'gcr.io/data8x-scratch/otter-srv'
timeout: 1200s
substitutions:
  _TAG_NAME: ""