apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gofer-claim
  namespace: grader-k8-namespace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi