apiVersion: v1
kind: PersistentVolume
metadata:
  name: otter-volume-set-by-script
  labels:
    name: otter-volume
spec:
  capacity:
    storage: 4Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: |-
      set-by-script
