apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gofer-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: gofer-volume