apiVersion: v1
kind: ConfigMap
metadata:
    name: otter-env
data:
    POST_GRADE: "True"
    VERBOSE_LOGGING: "True"
    EDX_URL: courses.edx.org
    AUTOGRADER_REPO: materials-x22-private
    AUTOGRADER_MATERIALS_SUBPATH: materials/x22
    AUTOGRADER_MATERIALS_URL: github.com/data-8/materials-x22-private/archive/main.tar.gz
    COURSE_CONFIG_PATH: /opt/materials-x22-private/8x-course-config.json
    GCP_PROJECT_ID: data8x-scratch
    VOLUME_PATH: /mnt/data
    OTTER_LOG_FILE: otter-service-logs.txt
    SERVER_LOG_FILE: tornado-server-log.txt
    ERROR_FILE: otter-service-errors.csv
    ERROR_PATH: ottererrors
    SUBMISSIONS_PATH: submissions
    DB_PATH: gradebook.db
    JUPYTERHUB_API_URL: https://hubv2.data8x.berkeley.edu/hub/api
    JUPYTERHUB_BASE_URL: https://hubv2.data8x.berkeley.edu
    JUPYTERHUB_API_TOKEN: ENC[AES256_GCM,data:BoAIe7qkLBu3LERrWx1dyz2huhRH9pP1I1vy9Esewus=,iv:mLfZstP7Dn/8+KQw8WO6g+rjbBftDL6AJkGWMNqE9IQ=,tag:b8p2LEzumhFcTsoOt7vWdA==,type:str]
    JUPYTERHUB_SERVICE_PREFIX: /services/gofer_nb/
    JUPYTERHUB_SERVICE_NAME: gofer_nb
    TEST_USER: 594aed203b01b16a7a025c2f3e037933
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/data8x-scratch/locations/global/keyRings/data8x-sops/cryptoKeys/otter-service
          created_at: "2022-06-21T16:24:52Z"
          enc: CiQA+mtdjwE8/LAgbn6nmkZJsgJTr13YRJMbnRNVHJmqgjh3EHcSSQCnWbpG4NNuIOLuZYyAMsL0kR1nvdAGJQuMYvQWjCoAOERipwcqRgnoNpQsk0tb805dE/AVhe4TMTc0RiAvO4zqMxpkeJDY6s0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-21T16:24:53Z"
    mac: ENC[AES256_GCM,data:jQzuZpth0Oe53aFq2eB44LfO3PgPWPkt+M5nGJOh2cNGKb6V6WNqAgHmkLaIvI1k0MBXA1mhG0+kgTxKmdlqaCmr1nOjyLX8X6HDL5Af0r/4L65KZs9Rpn0vUq214AAmh/4Yp7IFLC+nnoeUygY70sJyOWRjdXFfqDCFZ6TMgnw=,iv:OGZj4BfnpqCU2VebwaDGjFYCfG+MHoGrceV1pW9EflQ=,tag:ZcEfcu+avHrnkgjjJGnDkQ==,type:str]
    pgp: []
    encrypted_suffix: _TOKEN
    version: 3.7.1
