apiVersion: apps/v1
kind: Deployment
metadata:
  name: otter-pod
  labels:
    app: otter-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otter-srv
  template:
    metadata:
      labels:
        app: otter-srv
    spec:
      serviceAccountName: otter-k8-sa
      containers:
        - name: otter-srv
          image: gcr.io/data8x-scratch/otter-srv:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 8Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 8Gi
          ports:
            - containerPort: 10101
          envFrom:
            - configMapRef:
                name: otter-env
