apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofer-pod
  labels:
    app: gofer-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gofer-v2
  template:
    metadata:
      labels:
        app: gofer-v2
    spec:
      serviceAccountName: grader-k8-sa
      containers:
        - name: gofer-v2
          image: gcr.io/data8x-scratch/gofer:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 8Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 8Gi
          ports:
            - containerPort: 10101
          volumeMounts:
            - mountPath: "/mnt/data"
              name: gofer-mnt
          envFrom:
            - configMapRef:
                name: grader-env
      volumes:
        - name: gofer-mnt
          persistentVolumeClaim:
            claimName: gofer-claim
