apiVersion: v1
kind: Service
metadata:
  name: otter-lb
spec:
  selector:
    app: otter-srv
  ports:
    - port: 10101
      targetPort: 10101
  type: LoadBalancer
  loadBalancerIP: "34.134.165.169"
