gcloud beta container --project "data8x-scratch" clusters create "otter-cluster-v3" \
--region "us-central1" \
--no-enable-basic-auth \
--cluster-version "1.22.12-gke.2300" \
--release-channel "regular" \
--machine-type "e2-standard-2" \
--image-type "COS_CONTAINERD" \
--disk-type "pd-standard" \
--disk-size "100" \
--metadata disable-legacy-endpoints=true \
--scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
--max-pods-per-node "110" \
--num-nodes "1" \
--logging=SYSTEM,WORKLOAD \
--monitoring=SYSTEM \
--enable-ip-alias \
--network "projects/data8x-scratch/global/networks/default" \
--subnetwork "projects/data8x-scratch/regions/us-central1/subnetworks/default" \
--no-enable-intra-node-visibility \
--default-max-pods-per-node "110" \
--no-enable-master-authorized-networks \
--addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver,GcpFilestoreCsiDriver \
--enable-autoscaling \
--min-nodes "0" \
--max-nodes "1" \
--enable-autoupgrade \
--enable-autorepair \
--max-surge-upgrade 1 \
--max-unavailable-upgrade 0 \
--workload-pool "data8x-scratch.svc.id.goog" \
--workload-metadata GKE_METADATA \
--enable-shielded-nodes \
--node-locations "us-central1-a","us-central1-c","us-central1-f"